vich_uploader:
  db_driver: orm

  mappings:
    planning_pdf:
      uri_prefix: /_private/planning
      upload_destination: '%kernel.project_dir%/var/uploads/planning'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer